/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "platform_types.h"

#define RCC_BASE        0x40021000
#define GPIO_PORTA_BASE 0x40010800

typedef union{
	vuint32_t port;
	struct {
		vuint32_t reserved : 13;
		vuint32_t pin13 : 1;
	}pins;
}gpio_portx_ODR_U;

#define RCC_APB2ENR_R   *((vuint32_t *) (RCC_BASE + 0x18))
#define GPIO_PORTA_CRH  *((vuint32_t *) (GPIO_PORTA_BASE + 0x04))
gpio_portx_ODR_U* GPIO_PORTA_ODR_R = (gpio_portx_ODR_U*) (GPIO_PORTA_BASE + 0x0C);

int main(void)
{
	RCC_APB2ENR_R  |=  (1<<2);           /*set bit2*/
	GPIO_PORTA_CRH &= ~(0xf << 20);      /*reset bits 20-->24*/
	GPIO_PORTA_CRH |=  (2 << 20);        /*write 2 on bits 20-->24*/
	uint32_t i;
	for(;;){
		GPIO_PORTA_ODR_R->pins.pin13 = 1;/*led on*/
		for(i = 0 ; i < 100000; i++);    /*software delay*/
		GPIO_PORTA_ODR_R->pins.pin13 = 0;/*led off*/
		for(i = 0 ; i < 100000; i++);    /*software delay*/
	}
}
