/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "LCD.h"
#include "Button.h"
void wait(uint32_t);
int main(void)
{
	LCD_Config_t LCD_Config;
	LCD_Config.Display_control = Display_Control_D_On_C_On_B_On;
	LCD_Config.Entry_mode      = Entry_Mode_Inc_No_S;
	LCD_Config.function_set    = Function_Set_4bit_2line_5x8;
	LCD_Init(&LCD_Config);
	Button_Init();
	IRQ_happened = 1;
	/* Loop forever */
	for(;;){
		if(IRQ_happened){
			IRQ_happened = 0;
			wait(3000);
			LCD_Write_Command(LCD_Clear);
			LCD_Write_Command(LCD_Return_Home);
		}
	}
}
void wait(uint32_t time){
	uint8_t i ;
	while(time--){
		for(i = 0 ; i < 255; i++);
	}
}
