/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f103c6_GPIO_Driver.h"
#include "stm32f103x6.h"

void GPIO_Init(void);
void Clock_Init(void);
int main(void)
{
	Clock_Init();
	GPIO_Init();
	uint8_t flag1 = 0;
	/* Loop forever */
	for(;;){
		/*We Want to avoid starvation*/
		/*SW1 at PA1 pressed*/
		if((MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_Value_Low) && !flag1){
			/*Toggle led on portB1*/
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			/*Single Pressing*/
			flag1 = 1;
		}
		/*SW2 at PA13 pressed*/
		/*Multi Pressing*/
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == GPIO_PIN_Value_High){
			/*Toggle led on portB13*/
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_Value_High){
			flag1 = 0;
		}

		for(uint32_t i = 0; i < 20000; i++); /*delay to observe changes*/
	}
}
void GPIO_Init(void){

	GPIO_PinConfig_t Piny; /*a structure to hold configurations of pins*/

	/*Configure PORTA PIN1 as floating input pin*/
	/*Which is the default reset value*/
	Piny.pinNumber = GPIO_PIN_1;
	Piny.pinMode   = GPIO_PIN_MODE_IN_Floating;
	MCAL_GPIO_Init(GPIOA, &Piny);

	/*Configure PORTA PIN13 as floating input pin*/
	/*Which is the default reset value*/
	Piny.pinNumber = GPIO_PIN_13;
	Piny.pinMode   = GPIO_PIN_MODE_IN_Floating;
	MCAL_GPIO_Init(GPIOA, &Piny);

	/*Configure PORTB PIN1 as Push-Pull output pin*/
	Piny.pinNumber = GPIO_PIN_1;
	Piny.pinMode   = GPIO_PIN_MODE_Out_PushPull;
	Piny.pinOutSpeed = GPIO_PIN_OUT_SPEED_10MHZ;
	MCAL_GPIO_Init(GPIOB, &Piny);

	/*Configure PORTB PIN13 as Push-Pull output pin*/
	Piny.pinNumber = GPIO_PIN_13;
	Piny.pinMode   = GPIO_PIN_MODE_Out_PushPull;
	Piny.pinOutSpeed = GPIO_PIN_OUT_SPEED_10MHZ;
	MCAL_GPIO_Init(GPIOB, &Piny);
}

void Clock_Init(void){
	/*enable clock for ports A and B*/
	GPIOA_Clock_Enable;
	GPIOB_Clock_Enable;
}

